on:
  push:
    branches: [ master ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore 
    - name: pull sql images
      run: docker pull mcr.microsoft.com/mssql/server:2019-CU6-ubuntu-16.04; docker pull mcr.microsoft.com/mssql/server:2017-latest; docker pull mcr.microsoft.com/mssql/server:2019-latest
    - name: pull postgres images
      run: docker pull postgres:latest; docker pull postgres:alpine; docker pull bitnami/postgresql:latest
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Bard.Db
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: Bard.Db/Bard.Db.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
